# Generated by Django 2.2.1 on 2019-06-02 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mpi.models
import mpi.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mpi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=mpi.models.document_directory_path, validators=[mpi.validators.validate_file_document]),
        ),
        migrations.CreateModel(
            name='ResultDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to=mpi.models.document_directory_path, validators=[mpi.validators.validate_file_document])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
