# Generated by Django 2.2.2 on 2019-06-09 21:49

from django.db import migrations, models
import mpi.models


class Migration(migrations.Migration):

    dependencies = [
        ('mpi', '0002_auto_20190602_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultdocument',
            name='file',
            field=models.FileField(upload_to=mpi.models.resultDocument_directory_path),
        ),
    ]
