# Generated by Django 2.2.2 on 2019-06-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpi', '0003_auto_20190609_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultdocument',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resultdocument',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
