# Generated by Django 2.2.2 on 2019-06-09 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpi', '0004_auto_20190609_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultdocument',
            old_name='read',
            new_name='ready',
        ),
    ]
