# Generated by Django 2.2.2 on 2019-06-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpi', '0005_auto_20190609_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultdocument',
            name='nr_process',
            field=models.IntegerField(default=0),
        ),
    ]
